- name: one option, implied type, with input
  input:
    - {namespace: "abc123"}
  config:
    - name: Kubernetes Cluster
      items:
        - name: namespace
          title: Namespace
  responses:
    json: |
      [
              {
                  "description": "",
                  "filters": null,
                  "items": [
                      {
                          "affix": "",
                          "data_cmd": null,
                          "default": "",
                          "default_cmd": null,
                          "filters": null,
                          "help_text": "",
                          "hidden": false,
                          "is_excluded_from_support": false,
                          "items": null,
                          "multi_value": null,
                          "multiple": false,
                          "name": "namespace",
                          "props": null,
                          "readonly": false,
                          "recommended": false,
                          "required": false,
                          "test_proc": null,
                          "title": "Namespace",
                          "type": "text",
                          "value": "abc123",
                          "value_cmd": null,
                          "when": ""
                      }
                  ],
                  "name": "Kubernetes Cluster",
                  "test_proc": null,
                  "title": "",
                  "when": ""
              }
          ]
