apiVersion: v1
data:
  BACKUP_CLUSTER_NAME: default
  BASE_DN: ou=identities
  DJ_INSTANCE: ds
  DS_ENABLE_CONFIGSTORE: "true"
  DS_ENABLE_CTS: "true"
  DS_ENABLE_IDMREPO: "true"
  DS_ENABLE_USERSTORE: "true"
  DS_SET_SIZE: "1"
  OPENDJ_JAVA_ARGS: -Xmx512m
  SLACK_URL: null
kind: ConfigMap
metadata:
  name: ds
