apiVersion: v1
kind: Service
metadata:
  labels:
    app: ds
    component: ds
    vendor: forgerock
  name: ds
spec:
  clusterIP: None
  ports:
  - name: ldap
    port: 1389
    targetPort: 1389
  - name: djadmin
    port: 4444
    targetPort: 4444
  - name: ldaps
    port: 1636
    targetPort: 1636
  - name: metrics
    port: 8080
    protocol: TCP
  selector:
    app: ds-ds
    release: ds
