
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.6.0"
[[constraint]]
  name = "github.com/pkg/errors"
  branch = "master"

[[constraint]]
  name = "github.com/go-stack/stack"
  version = "1.7.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/mholt/archiver"
  revision = "e4ef56d48eb029648b0e895bb0b6a393ef0829c3"

[[constraint]]
  name = "github.com/docker/docker"
  revision = "4047cede65862aa0ea5616297d7c0f3b12526ad4"

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

## Godep-related pain, waiting on upstream fix in dep
#[[override]]
#  name = "github.com/ugorji/go"
#  revision = "8c0409fcbb70099c748d71f714529204975f6c3f"

[[constraint]]
  name = "github.com/google/go-github"
  version = "15.0.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.9.1"

# Overrides for Kustomize & Helm
[[override]]
  name = "k8s.io/kubernetes"
  version = "1.10.6"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.10.6"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.6"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.10.6"

[[override]]
  name = "k8s.io/apimachinery"
  # revision to include dependencies for Kustomize
  # See here: https://github.com/kubernetes/apimachinery/commit/bca10bed01016dcaebb845433499fbb2a6343139
  revision = "bca10bed01016dcaebb845433499fbb2a6343139"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.6"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "1.5.1"
