---
# Source: elastic-stack/charts/elasticsearch/templates/client-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch
    chart: elasticsearch-1.16.0
    component: "client"
    heritage: Tiller
    release: elastic-stack
  name: elastic-stack-elasticsearch-client
