---
# Source: elastic-stack/charts/elasticsearch/templates/client-svc.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
    chart: elasticsearch-1.15.1
    component: "client"
    heritage: Tiller
    release: elastic-stack
  name: elastic-stack-elasticsearch-client

spec:
  ports:
    - name: http
      port: 9200
      targetPort: http
  selector:
    app: elasticsearch
    component: "client"
    release: elastic-stack
  type: ClusterIP
  