---
# Source: elastic-stack/charts/elasticsearch/templates/master-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch
    chart: elasticsearch-1.15.1
    component: "master"
    heritage: Tiller
    release: elastic-stack
  name: elastic-stack-elasticsearch-master
