##---
# Source: modify-chart/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: -modify-chart
  labels:
    app: modify-chart
    chart: modify-chart-0.1.0
    release: 
    heritage: Tiller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: modify-chart
      release: 
  template:
    metadata:
      labels:
        app: modify-chart
        release: 
    spec:
      containers:
        - name: modify-chart
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
            
