apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: security
    release: istio
  name: istio-citadel-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-citadel-default
subjects:
- kind: ServiceAccount
  name: istio-citadel-service-account
  namespace: default
