---
# Source: istio/charts/security/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-citadel-service-account
  namespace: default
  labels:
    app: security
    chart: security
    heritage: Tiller
    release: istio
