
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: cert-manager-webhook-ca
  namespace: "cert-manager"
  labels:
    app: webhook
    chart: webhook-v0.7.0
    release: cert-manager
    heritage: Tiller
spec:
  ca:
    secretName: cert-manager-webhook-ca
