kind: ""
apiversion: ""
patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRole
    name: cert-manager-cainjector
  path: chart-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRole
    name: cert-manager-cainjector
  path: heritage-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: cert-manager-edit
  path: chart-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: cert-manager-edit
  path: heritage-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: cert-manager-view
  path: chart-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: cert-manager-view
  path: heritage-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: cert-manager-webhook:webhook-requester
  path: chart-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: cert-manager-webhook:webhook-requester
  path: heritage-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRole
    name: cert-manager
  path: chart-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRole
    name: cert-manager
  path: heritage-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRoleBinding
    name: cert-manager-cainjector
  path: chart-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRoleBinding
    name: cert-manager-cainjector
  path: heritage-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRoleBinding
    name: cert-manager-webhook:auth-delegator
  path: chart-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRoleBinding
    name: cert-manager-webhook:auth-delegator
  path: heritage-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRoleBinding
    name: cert-manager
  path: chart-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRoleBinding
    name: cert-manager
  path: heritage-patch.json
- target:
    group: apps
    version: v1beta1
    kind: Deployment
    namespace: cert-manager
    name: cert-manager-cainjector
  path: chart-patch.json
- target:
    group: apps
    version: v1beta1
    kind: Deployment
    namespace: cert-manager
    name: cert-manager-cainjector
  path: heritage-patch.json
- target:
    group: apps
    version: v1beta1
    kind: Deployment
    namespace: cert-manager
    name: cert-manager
  path: chart-patch.json
- target:
    group: apps
    version: v1beta1
    kind: Deployment
    namespace: cert-manager
    name: cert-manager
  path: heritage-patch.json
- target:
    group: apps
    version: v1beta1
    kind: Deployment
    namespace: cert-manager
    name: cert-manager-webhook
  path: chart-patch.json
- target:
    group: apps
    version: v1beta1
    kind: Deployment
    namespace: cert-manager
    name: cert-manager-webhook
  path: heritage-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: RoleBinding
    namespace: kube-system
    name: cert-manager-webhook:webhook-authentication-reader
  path: chart-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: RoleBinding
    namespace: kube-system
    name: cert-manager-webhook:webhook-authentication-reader
  path: heritage-patch.json
- target:
    version: v1
    kind: Service
    namespace: cert-manager
    name: cert-manager-webhook
  path: chart-patch.json
- target:
    version: v1
    kind: Service
    namespace: cert-manager
    name: cert-manager-webhook
  path: heritage-patch.json
- target:
    version: v1
    kind: ServiceAccount
    namespace: cert-manager
    name: cert-manager-cainjector
  path: chart-patch.json
- target:
    version: v1
    kind: ServiceAccount
    namespace: cert-manager
    name: cert-manager-cainjector
  path: heritage-patch.json
- target:
    version: v1
    kind: ServiceAccount
    namespace: cert-manager
    name: cert-manager
  path: chart-patch.json
- target:
    version: v1
    kind: ServiceAccount
    namespace: cert-manager
    name: cert-manager
  path: heritage-patch.json
- target:
    version: v1
    kind: ServiceAccount
    namespace: cert-manager
    name: cert-manager-webhook
  path: chart-patch.json
- target:
    version: v1
    kind: ServiceAccount
    namespace: cert-manager
    name: cert-manager-webhook
  path: heritage-patch.json
- target:
    group: admissionregistration.k8s.io
    version: v1beta1
    kind: ValidatingWebhookConfiguration
    name: cert-manager-webhook
  path: chart-patch.json
- target:
    group: admissionregistration.k8s.io
    version: v1beta1
    kind: ValidatingWebhookConfiguration
    name: cert-manager-webhook
  path: heritage-patch.json
bases:
- ../../base
