project_name: ship
release:
  github:
    owner: replicatedhq
    name: ship
brew:
  github:
    owner: replicatedhq
    name: homebrew-ship
  folder: Formula
  homepage: https://ship.replicated.com/
  description: Deploy 3rd party applications through modern pipelines
  test: |
    system "#{bin}/ship", "version"
builds:
- goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - "386"
  env:
   - CGO_ENABLED=0
  main: cmd/ship/main.go
  ldflags: -s -w 
    -X github.com/replicatedhq/ship/pkg/version.version={{.Version}}
    -X github.com/replicatedhq/ship/pkg/version.gitSHA={{.Commit}}
    -X github.com/replicatedhq/ship/pkg/version.buildTime={{.Date}}
    -extldflags "-static"
  flags: -tags netgo -installsuffix netgo
  binary: ship
  hooks: {}
archive:
  format: tar.gz
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}-alpha'
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
dockers:
  - image: replicated/ship
    dockerfile: deploy/Dockerfile
    tag_templates:
      - "alpha"
      - "alpha-slim"
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
