---
# Source: concourse/charts/postgresql/templates/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: concourse-postgresql
  labels:
    app: postgresql
    chart: postgresql-0.13.1
    release: concourse
    heritage: Tiller
type: Opaque
data:
  
  postgres-password:  "Y29uY291cnNl"
  
