##---
# Source: modify-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: -modify-chart
  labels:
    app: modify-chart
    chart: modify-chart-0.1.0
    release: 
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: modify-chart
    release: 
