kind: ""
apiversion: ""
patchesJson6902:
- target:
    version: v1
    kind: ConfigMap
    name: concourse-postgresql
  path: chart-patch.json
- target:
    version: v1
    kind: ConfigMap
    name: concourse-postgresql
  path: heritage-patch.json
- target:
    group: extensions
    version: v1beta1
    kind: Deployment
    name: concourse-postgresql
  path: chart-patch.json
- target:
    group: extensions
    version: v1beta1
    kind: Deployment
    name: concourse-postgresql
  path: heritage-patch.json
- target:
    version: v1
    kind: PersistentVolumeClaim
    name: concourse-postgresql
  path: chart-patch.json
- target:
    version: v1
    kind: PersistentVolumeClaim
    name: concourse-postgresql
  path: heritage-patch.json
- target:
    version: v1
    kind: Secret
    name: concourse-postgresql
  path: chart-patch.json
- target:
    version: v1
    kind: Secret
    name: concourse-postgresql
  path: heritage-patch.json
- target:
    version: v1
    kind: Service
    name: concourse-postgresql
  path: chart-patch.json
- target:
    version: v1
    kind: Service
    name: concourse-postgresql
  path: heritage-patch.json
- target:
    version: v1
    kind: Secret
    name: concourse-concourse
  path: chart-patch.json
- target:
    version: v1
    kind: Secret
    name: concourse-concourse
  path: heritage-patch.json
- target:
    group: extensions
    version: v1beta1
    kind: Deployment
    name: concourse-web
  path: chart-patch.json
- target:
    group: extensions
    version: v1beta1
    kind: Deployment
    name: concourse-web
  path: heritage-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRole
    name: concourse-web
  path: chart-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRole
    name: concourse-web
  path: heritage-patch.json
- target:
    version: v1
    kind: ServiceAccount
    name: concourse-web
  path: chart-patch.json
- target:
    version: v1
    kind: ServiceAccount
    name: concourse-web
  path: heritage-patch.json
- target:
    version: v1
    kind: Service
    name: concourse-web
  path: chart-patch.json
- target:
    version: v1
    kind: Service
    name: concourse-web
  path: heritage-patch.json
- target:
    group: policy
    version: v1beta1
    kind: PodDisruptionBudget
    name: concourse-worker
  path: chart-patch.json
- target:
    group: policy
    version: v1beta1
    kind: PodDisruptionBudget
    name: concourse-worker
  path: heritage-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: Role
    name: concourse-worker
  path: chart-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: Role
    name: concourse-worker
  path: heritage-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: RoleBinding
    name: concourse-worker
  path: chart-patch.json
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: RoleBinding
    name: concourse-worker
  path: heritage-patch.json
- target:
    version: v1
    kind: ServiceAccount
    name: concourse-worker
  path: chart-patch.json
- target:
    version: v1
    kind: ServiceAccount
    name: concourse-worker
  path: heritage-patch.json
- target:
    group: apps
    version: v1beta1
    kind: StatefulSet
    name: concourse-worker
  path: chart-patch.json
- target:
    group: apps
    version: v1beta1
    kind: StatefulSet
    name: concourse-worker
  path: heritage-patch.json
- target:
    version: v1
    kind: Service
    name: concourse-worker
  path: chart-patch.json
- target:
    version: v1
    kind: Service
    name: concourse-worker
  path: heritage-patch.json
bases:
- ../../base
