##---
# Source: basic/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: basic
  labels:
    app: basic
    chart: basic-0.1.0
    release: basic
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic
      release: basic
  template:
    metadata:
      labels:
        app: basic
        release: basic
    spec:
      containers:
        - name: basic
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
            
