apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: istio-security
    release: istio
  name: istio-security-post-install-role-binding-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-security-post-install-default
subjects:
- kind: ServiceAccount
  name: istio-security-post-install-account
  namespace: default
