apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "3"
  labels:
    app: security
    release: istio
  name: istio-cleanup-secrets
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: security
        release: istio
      name: istio-cleanup-secrets
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          kubectl get secret --all-namespaces | grep "istio.io/key-and-cert" |  while read -r entry; do
            ns=$(echo $entry | awk '{print $1}');
            name=$(echo $entry | awk '{print $2}');
            kubectl delete secret $name -n $ns;
          done
        image: quay.io/coreos/hyperkube:v1.7.6_coreos.0
        name: hyperkube
      restartPolicy: OnFailure
      serviceAccountName: istio-cleanup-secrets-service-account
