apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "2"
  labels:
    app: security
    chart: security
    heritage: Tiller
    release: istio
  name: istio-cleanup-secrets-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-cleanup-secrets-default
subjects:
- kind: ServiceAccount
  name: istio-cleanup-secrets-service-account
  namespace: default
