kind: ""
apiversion: ""
resources:
- charts/galley/templates/clusterrole.yaml
- charts/galley/templates/clusterrolebinding.yaml
- charts/galley/templates/configmap.yaml
- charts/galley/templates/deployment.yaml
- charts/galley/templates/service.yaml
- charts/galley/templates/serviceaccount.yaml
- charts/gateways/templates/autoscale.yaml
- charts/gateways/templates/clusterrole.yaml
- charts/gateways/templates/clusterrolebindings.yaml
- charts/gateways/templates/deployment.yaml
- charts/gateways/templates/service.yaml
- charts/gateways/templates/serviceaccount.yaml
- charts/mixer/templates/autoscale.yaml
- charts/mixer/templates/clusterrole.yaml
- charts/mixer/templates/clusterrolebinding.yaml
- charts/mixer/templates/config.yaml
- charts/mixer/templates/deployment.yaml
- charts/mixer/templates/service.yaml
- charts/mixer/templates/serviceaccount.yaml
- charts/pilot/templates/autoscale.yaml
- charts/pilot/templates/clusterrole.yaml
- charts/pilot/templates/clusterrolebinding.yaml
- charts/pilot/templates/deployment.yaml
- charts/pilot/templates/service.yaml
- charts/pilot/templates/serviceaccount.yaml
- charts/prometheus/templates/clusterrole.yaml
- charts/prometheus/templates/clusterrolebindings.yaml
- charts/prometheus/templates/configmap.yaml
- charts/prometheus/templates/deployment.yaml
- charts/prometheus/templates/service.yaml
- charts/prometheus/templates/serviceaccount.yaml
- charts/security/templates/cleanup-secrets.yaml
- charts/security/templates/clusterrole.yaml
- charts/security/templates/clusterrolebinding.yaml
- charts/security/templates/configmap.yaml
- charts/security/templates/create-custom-resources-job.yaml
- charts/security/templates/deployment.yaml
- charts/security/templates/service.yaml
- charts/security/templates/serviceaccount.yaml
- charts/sidecarInjectorWebhook/templates/clusterrole.yaml
- charts/sidecarInjectorWebhook/templates/clusterrolebinding.yaml
- charts/sidecarInjectorWebhook/templates/deployment.yaml
- charts/sidecarInjectorWebhook/templates/mutatingwebhook.yaml
- charts/sidecarInjectorWebhook/templates/service.yaml
- charts/sidecarInjectorWebhook/templates/serviceaccount.yaml
- configmap.yaml
- crds.yaml
- sidecar-injector-configmap.yaml
