kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- charts/galley/templates/clusterrole.yaml
- charts/galley/templates/clusterrolebinding.yaml
- charts/galley/templates/configmap.yaml
- charts/galley/templates/deployment.yaml
- charts/galley/templates/service.yaml
- charts/galley/templates/serviceaccount.yaml
- charts/gateways/templates/ClusterRole-istio-egressgateway-default.yaml
- charts/gateways/templates/ClusterRole-istio-ingressgateway-default.yaml
- charts/gateways/templates/ClusterRoleBinding-istio-egressgateway-default.yaml
- charts/gateways/templates/ClusterRoleBinding-istio-ingressgateway-default.yaml
- charts/gateways/templates/Deployment-istio-egressgateway.yaml
- charts/gateways/templates/Deployment-istio-ingressgateway.yaml
- charts/gateways/templates/HorizontalPodAutoscaler-istio-egressgateway.yaml
- charts/gateways/templates/HorizontalPodAutoscaler-istio-ingressgateway.yaml
- charts/gateways/templates/Service-istio-egressgateway.yaml
- charts/gateways/templates/Service-istio-ingressgateway.yaml
- charts/gateways/templates/ServiceAccount-istio-egressgateway-service-account.yaml
- charts/gateways/templates/ServiceAccount-istio-ingressgateway-service-account.yaml
- charts/mixer/templates/Deployment-istio-policy.yaml
- charts/mixer/templates/Deployment-istio-telemetry.yaml
- charts/mixer/templates/DestinationRule-istio-policy.yaml
- charts/mixer/templates/DestinationRule-istio-telemetry.yaml
- charts/mixer/templates/HorizontalPodAutoscaler-istio-policy.yaml
- charts/mixer/templates/HorizontalPodAutoscaler-istio-telemetry.yaml
- charts/mixer/templates/Service-istio-policy.yaml
- charts/mixer/templates/Service-istio-telemetry.yaml
- charts/mixer/templates/attributemanifest-istioproxy.yaml
- charts/mixer/templates/attributemanifest-kubernetes.yaml
- charts/mixer/templates/clusterrole.yaml
- charts/mixer/templates/clusterrolebinding.yaml
- charts/mixer/templates/handler-kubernetesenv.yaml
- charts/mixer/templates/handler-prometheus.yaml
- charts/mixer/templates/handler-stdio.yaml
- charts/mixer/templates/kubernetes-attributes.yaml
- charts/mixer/templates/logentry-accesslog.yaml
- charts/mixer/templates/logentry-tcpaccesslog.yaml
- charts/mixer/templates/metric-requestcount.yaml
- charts/mixer/templates/metric-requestduration.yaml
- charts/mixer/templates/metric-requestsize.yaml
- charts/mixer/templates/metric-responsesize.yaml
- charts/mixer/templates/metric-tcpbytereceived.yaml
- charts/mixer/templates/metric-tcpbytesent.yaml
- charts/mixer/templates/rule-kubeattrgenrulerule.yaml
- charts/mixer/templates/rule-promhttp.yaml
- charts/mixer/templates/rule-promtcp.yaml
- charts/mixer/templates/rule-stdio.yaml
- charts/mixer/templates/rule-stdiotcp.yaml
- charts/mixer/templates/rule-tcpkubeattrgenrulerule.yaml
- charts/mixer/templates/serviceaccount.yaml
- charts/pilot/templates/autoscale.yaml
- charts/pilot/templates/clusterrole.yaml
- charts/pilot/templates/clusterrolebinding.yaml
- charts/pilot/templates/deployment.yaml
- charts/pilot/templates/service.yaml
- charts/pilot/templates/serviceaccount.yaml
- charts/prometheus/templates/clusterrole.yaml
- charts/prometheus/templates/clusterrolebindings.yaml
- charts/prometheus/templates/configmap.yaml
- charts/prometheus/templates/deployment.yaml
- charts/prometheus/templates/service.yaml
- charts/prometheus/templates/serviceaccount.yaml
- charts/security/templates/ClusterRole-istio-cleanup-secrets-default.yaml
- charts/security/templates/ClusterRole-istio-security-post-install-default.yaml
- charts/security/templates/ClusterRoleBinding-istio-cleanup-secrets-default.yaml
- charts/security/templates/ClusterRoleBinding-istio-security-post-install-role-binding-default.yaml
- charts/security/templates/Job-istio-cleanup-secrets.yaml
- charts/security/templates/Job-istio-security-post-install.yaml
- charts/security/templates/ServiceAccount-istio-cleanup-secrets-service-account.yaml
- charts/security/templates/ServiceAccount-istio-security-post-install-account.yaml
- charts/security/templates/clusterrole.yaml
- charts/security/templates/clusterrolebinding.yaml
- charts/security/templates/configmap.yaml
- charts/security/templates/deployment.yaml
- charts/security/templates/service.yaml
- charts/security/templates/serviceaccount.yaml
- charts/sidecarInjectorWebhook/templates/clusterrole.yaml
- charts/sidecarInjectorWebhook/templates/clusterrolebinding.yaml
- charts/sidecarInjectorWebhook/templates/deployment.yaml
- charts/sidecarInjectorWebhook/templates/mutatingwebhook.yaml
- charts/sidecarInjectorWebhook/templates/service.yaml
- charts/sidecarInjectorWebhook/templates/serviceaccount.yaml
- configmap.yaml
- crds.yaml
- sidecar-injector-configmap.yaml
