---
# Source: istio/charts/gateways/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-egressgateway-service-account
  namespace: default
  labels:
    app: gateways
    chart: gateways
    heritage: Tiller
    release: istio